// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Whi_vAwXyx0awdVfkjXrW0MUqPEatdw',
    appId: '1:867235041226:web:8ed292d1bc5b9f826b4933',
    messagingSenderId: '867235041226',
    projectId: 'sadekappsystem',
    authDomain: 'sadekappsystem.firebaseapp.com',
    storageBucket: 'sadekappsystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoxyGg6e4bh2ZUokYjB5ME6kbVMhVY-q0',
    appId: '1:867235041226:android:43055f29652308476b4933',
    messagingSenderId: '867235041226',
    projectId: 'sadekappsystem',
    storageBucket: 'sadekappsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAGqOlLIVdCzKHdjACtGDca-OJec33p_c',
    appId: '1:867235041226:ios:7745204e4adc6bb36b4933',
    messagingSenderId: '867235041226',
    projectId: 'sadekappsystem',
    storageBucket: 'sadekappsystem.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAGqOlLIVdCzKHdjACtGDca-OJec33p_c',
    appId: '1:867235041226:ios:7745204e4adc6bb36b4933',
    messagingSenderId: '867235041226',
    projectId: 'sadekappsystem',
    storageBucket: 'sadekappsystem.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

}